[package]
name = "zero2prod"
version = "0.1.0"
authors = ["LukeMathWalker <rust@lpalmieri.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "4.0.0-beta.20"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
serde = "1.0.133"
config = { version = "0.11.0", default-features = false, features = ["yaml"] }
sqlx = { version = "0.5.10", default-features = false, features = [ "runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"] }
uuid = { version = "0.8.2", features = ["v4"] }
chrono = "0.4.19"
log = "0.4.14"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.6", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3.2"
tracing-log = "0.1.2"
serde-aux = "3.0.1"
unicode-segmentation = "1.8.0"
tracing-actix-web = "0.5.0-beta.10"
secrecy = { version = "0.8.0", features = ["serde"] }

[dev-dependencies]
reqwest = { version = "0.11.9", features = ["json"] }
claim = "0.5.0"
once_cell = "1.9.0"
